---
title: "Lab_2"
format: html
editor: visual
---


```{r}
library(dplyr)
```
```{r}
tree_dat%>%summarise(n=n())
```

```{r}
#1
tree_dat%>%
  filter(standID==1)%>%
  tally()
```

```{r}
#2
tree_count1<-tree_dat%>%
  filter(standID==1)

print(tree_count1)
```

```{r}
#3
tree_spec1<-tree_dat%>%
  filter(species%in%c("ABBA","PIST"))%>%
  count(species)

print(tree_spec1)
```

```{r}
#4
last_year<-max(tree_dat$year,na.rm = TRUE)

tree_dat%>%
  filter(year==last_year,age>200)%>%
  tally()

```

```{r}
#5
oldest_tree<-tree_dat%>%
  slice_max(order_by=age,n=1)

print(oldest_tree)
```

```{r}
#6
five_old_trees<-tree_dat%>%
  filter(year==2001)%>%
  slice_max(order_by=age,n=5)

print(five_old_trees)
```

```{r}
#7
sample_size<-tree_dat%>%
  filter(year==2002)%>%
  slice_sample(prop=0.3)

print(sample_size)
```

```{r}
#8
stand5_2007 <- tree_dat %>%
  filter(year == 2007) %>%
  filter(standID == 5) %>%
  arrange(rad_ib) %>%
  slice_head(n = 3)

print(stand5_2007)
```

```{r}
#9
threesmall_trees <- tree_dat %>%
  select(treeID, stand, year, rad_ib)%>%
  filter(stand == 3, year == 2007) %>%
  slice_min(order_by = rad_ib, n =3)

print(threesmall_trees)

```

```{r}
#10
dont_stand <- tree_dat %>%
  select(-stand)

glimpse(dont_stand)
```


#11


```{r}
#12

selected_columns <- tree_dat %>%
  select(contains("ID"), contains("stand"))

glimpse(selected_columns)

```

```{r}
#13

tree_dat_two <- tree_dat %>%
  rename(
    rad_ib_cm = rad_ib,
    inc_kg = inc)

glimpse(tree_dat_two)
```

```{r}
#14

mean_BA_potr_2007 <- tree_dat %>%  mutate(
    DBH = 2 * rad_ib,
    BA_m2 = 0.00007854 * DBH^2) %>%
  filter(species == "POTR", year == 2007) %>%
  summarise(mean_BA = mean(BA_m2, na.rm = TRUE))

print(mean_BA_potr_2007)

```

```{r}
#15

established_count <- tree_dat %>%
  mutate(established = if_else(age > 5, TRUE, FALSE))

print(established_count)

```

```{r}
#16

dbh_class_count <- tree_dat %>%
  mutate(DBH_class = case_when(
    DBH < 10 ~ "Small",
    DBH >= 10 & DBH < 30 ~ "Medium",
    DBH >= 30 ~ "Large"
  )) %>%
  filter(year == 2007)

print(dbh_class_count)

```

```{r}
#17

dbh_stats_2007 <- tree_dat %>%
  filter(year == 2007) %>%
  summarise(
    mean_dbh = mean(DBH, na.rm = TRUE),
    sd_dbh = sd(DBH, na.rm = TRUE))

print(dbh_stats_2007)

```

```{r}
#18

oldest_species_2003 <- tree_dat %>%
  filter(year == 2003) %>%
  group_by(species) %>%
  summarise(mean_age = mean(age, na.rm = TRUE)) %>%
  arrange(desc(mean_age)) %>%
  head(3)

print(oldest_species_2003)

```

```{r}
#19

year_summary <- tree_dat %>%
  summarise(
    num_unique_years = n_distinct(year),
    first_year = min(year),
    last_year = max(year))

print(year_summary)

```

```{r}
#20

stand_years <- tree_dat %>%
  group_by(standID) %>%
  summarise(unique_years = n_distinct(year)) %>%
  ungroup()

print(stand_years)

```
